name: Nahlásit chybu v instalaci překladu (češtiny)
description: Instalace překladu (češtiny) nefunguje jak jste očekávali? Nahlašte nám chybu
labels:
  - instalace
title: <Napište strun0 shrnutí vašeho problému (v jedné větě).>
body:

  - type: textarea
    id: cojstedelali
    attributes:
      label: Co jste dělali
      description: >-
        Popište co jste dělali, například:  
        _Pokusil jsem se instalovat češtinu do hry. Instalace se nezdařila._
    validations:
      required: true

  - type: textarea
    id: cojsteocekavali
    attributes:
      label: Co jste očekávali
      description: >-
        Uveďte co jste očekávali, například:  
        _Úspěšnou instalaci češtiny._
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot s chybovou hláškou při instalaci
      description: >-
        Přiložte prosím screenshot, nebo screenshoty ve formátu PNG, dokumentující váš problém. **Všechny** chybové hlášky, které se zobrazily během instalace češtiny jsou pro nás důležité.  
        Vyhrazujeme si právo uzavřít tento problém, pokud nebude přiložen screenshot.
      placeholder: |-
        Přetáhněte myší screenshot ve formátu PNG sem.
    validations:
      required: true

  - type: dropdown
    id: distribution
    attributes:
      label: Typ distribuce hry
      description: >-
        Vyberte typ distribuce hry ve které máte problém.
      multiple: false
      options:
        - Originální distribuce na CD/DVD (non-steam) [nepodporováno]
        - Steam
        - GOG.com (neveřejná beta)

  - type: checkboxes
    id: usedplugins
    attributes:
      label: Jaká rozšíření (pluginy) ve hře máte **aktivní**?
      description: >-
        Vyberte jaká rozšíření (pluginy) máte ve hře **aktivní**.
      options:
        - label: >-
            Morrowind.
          required: true
        - label: >-
            Tribunal.
          required: false
        - label: >-
            Bloodmoon.
          required: false
        - label: >-
            A další doplněk, či doplňky, mimo překladu (češtiny).
          required: false

  - type: textarea
    id: 3rdplugin
    attributes:
      label: Jaké doplňky třetích stran uživáte?
      description: >-
        Pokud jste uvedli v předchozím formuláři, že používáte doplňky třetích stran, uveďte jaké doplňky to jsou.
    validations:
      required: false

  - type: dropdown
    id: operatingsystem
    attributes:
      label: Operační systém
      description: >-
        Vyberte váš operační systém.
      multiple: false
      options:
        - Windows 10 x64
        - Windows 11 x64
          required: true

  - type: checkboxes
    id: dotnetfw
    attributes:
      label: Máte nainstalován Microsoft .NET Framework verze 4.6, nebo novější?
      description: >-
        Ujistěte se, že ve vašem operačním systému máte nainstalován Microsoft .NET Framework verze 4.6, nebo novější.  
        Microsoft .NET Framework je součástí systémů Windows 10 a Windows 11.
      options:
        - label: >-
            Potvrzuji, mám nainstalován Microsoft .NET Framework verze 4.6, nebo novější.
          required: true

  - type: checkboxes
    id: tes3czechversion
    attributes:
      label: Máte nainstalovanou aktuální (nejnovější) verzi překladu (češtiny)?
      description: >-
        Ujistěte se, že máte nainstalovanou [aktuální (nejnovější) verzi překladu (češtiny)](http://zob.ec/morrcz).
      options:
        - label: >-
            Potvrzuji, používám aktuální verzi překladu (češtiny).
          required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Než vytvoříte toto oznámení o chybě
      description: >-
        Ujistěte se, že vaše hlášení o chybě splňuje všechny následující požadavky. Pokud si nejste jisti,
         co konkrétní požadavek znamená, klikněte na odkaz abyste se o něm dozvěděli a pochopili,
         proč je to nutné, než potvrdíte tuto volbu.  
         Dodržováním těchto podmínek ušetříte nám i vám drahocenný čas.
      options:
        - label: >-
            Přečetl jsem a řídil jsem se článkem [TES3 Morrowind Czech: Máte potíže?](https://doc.michalzobec.cz/tes3-morrowind-czech-mate-potize-57) pro hlášení chyb v překladu.
          required: true
        - label: >-
            Před založením tohoto oznámení o chybě jsem se ujistil v [uživatelské příručce](https://doc.michalzobec.cz/tes3-morrowind-czech-uzivatelska-prirucka-8),
            a [poznámkách k vydání](https://doc.michalzobec.cz/tes3-morrowind-czech-poznamky-k-vydani-12), že mnou popsaný problém ještě nikdo předemnou nehlásil.
          required: true
        - label: >-
            Ujistil jsem se, že hru hraji pouze v podporovaném scénáři, tedy bez žádného doplňku, kromě samotného překladu a datadisků Tribunal a Bloodmoon,
            jak je popsáno v [uživatelské příručce](https://doc.michalzobec.cz/tes3-morrowind-czech-uzivatelska-prirucka-8).
          required: true
        - label: >-
            Přiložil jsem screenshot.
          required: true
